### ISSUE TITLE
[nextcloud] Cache Error

### ISSUE THREAD

**Issue by ghost** [Wonderfall/dockerfiles#118]
i get these Messages 
```
Info	cli	Memcache \OC\Memcache\APCu not available for distributed cache	
Info	cli	Memcache \OC\Memcache\APCu not available for local cache	
```

thats in my config.php
```
  'memcache.local' => '\OC\Memcache\APCu',
  'memcache.locking' => '\OC\Memcache\Redis',
  'redis' => 
  array (
    'host' => '/tmp/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
  ),
```

**Comment by skriems** [comment]
Try adding this line:
`'memcache.distributed' => '\OC\Memcache\APCu',`

**Comment by Wonderfall** [comment]
What's the output of `php7 -m` ?

**Comment by tbrasser** [comment]
I have the same issue since yesterday. (daily build)

Updating permissions...
Updating permissions in /nextcloud...
Permissions in /data are correct.
Permissions in /config are correct.
Permissions in /apps2 are correct.
Updating permissions in /etc/nginx...
Updating permissions in /etc/php7.1...
Updating permissions in /var/log...
Updating permissions in /var/lib/nginx...
Updating permissions in /tmp...
Updating permissions in /etc/s6.d...
Done updating permissions.
PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php7.1/modules/apcu.so' - Error loading shared library /usr/lib/php7.1/modules/apcu.so: No such file or directory in Unknown on line 0

Nextcloud is already latest version

PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php7.1/modules/apcu.so' - Error loading shared library /usr/lib/php7.1/modules/apcu.so: No such file or directory in Unknown on line 0

[25-Feb-2017 13:38:51] NOTICE: PHP message: PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php7.1/modules/apcu.so' - Error loading shared library /usr/lib/php7.1/modules/apcu.so: No such file or directory in Unknown on line 0

**Comment by Wonderfall** [comment]
This will be fixed in the next build (manually triggered right now). https://github.com/Wonderfall/dockerfiles/commit/814c4bb67932efe87adedd4e9aa964b814e151fa
Somehow `pcre-dev` now needs to be explicitly installed otherwise the `apcu` module doesn't build.

However I don't think this is related to the OP.
