### ISSUE TITLE
[nextcloud] - iOS App does not sync anymore

### ISSUE THREAD

**Issue by thiesschneider** [Wonderfall/dockerfiles#128]
Hey there,

since you removed redis the nextcloud app is showing an "internal server error". 
In the logging section of the administration panel there are also many errors. For example this webdav error:
```
RedisException: Redis server went away
/nextcloud/lib/private/Memcache/Redis.php - line 114: Redis->incrBy('0b9f1565b238119...', 1)
/nextcloud/lib/private/Lock/MemcacheLockingProvider.php - line 73: OC\Memcache\Redis->inc('files/7334b52da...')
/nextcloud/lib/private/Files/Storage/Common.php - line 680: OC\Lock\MemcacheLockingProvider->acquireLock('files/7334b52da...', 1)
/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 588: OC\Files\Storage\Common->acquireLock('files/Photos/20...', 1, Object(OC\Lock\MemcacheLockingProvider))
/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 588: OC\Files\Storage\Wrapper\Wrapper->acquireLock('files/Photos/20...', 1, Object(OC\Lock\MemcacheLockingProvider))
/nextcloud/lib/private/Files/View.php - line 1894: OC\Files\Storage\Wrapper\Wrapper->acquireLock('files/Photos/20...', 1, Object(OC\Lock\MemcacheLockingProvider))
/nextcloud/lib/private/Files/View.php - line 1997: OC\Files\View->lockPath('Photos/2017/02/...', 1, false)
/nextcloud/lib/private/Files/View.php - line 1295: OC\Files\View->lockFile('Photos/2017/02/...', 1)
/nextcloud/lib/private/Files/View.php - line 1342: OC\Files\View->getCacheEntry(Object(OCA\Files_Trashbin\Storage), 'files/Photos/20...', 'Photos/2017/02/...')
/nextcloud/apps/dav/lib/Connector/Sabre/ObjectTree.php - line 160: OC\Files\View->getFileInfo('/lisa/files/Pho...')
/nextcloud/apps/dav/lib/Connector/Sabre/LockPlugin.php - line 60: OCA\DAV\Connector\Sabre\ObjectTree->getNodeForPath('Photos/2017/02/...')
[internal function] OCA\DAV\Connector\Sabre\LockPlugin->getLock(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)
/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/nextcloud/apps/dav/appinfo/v1/webdav.php - line 60: Sabre\DAV\Server->exec()
/nextcloud/remote.php - line 165: require_once('/nextcloud/apps...')
{main}
```

Do I have to wait until redis is enabled again or do I have to build my own redis container?

thx in advance!

**Comment by Wonderfall** [comment]
I removed the redis server (the php redis extension is still present) because it is better to have it in another container (for instance), it's better for scalability. I've configured Nextcloud with a redis container (`redis:alpine`  image) and it works flawlessly (example provided in the new README update).

Alternatively you can remove redis configuration in config.php.

**Comment by thiesschneider** [comment]
I configured a redis container and now it is all running again!
Thx

**Comment by robclay** [comment]
After you remove the redis server , how do you force the file to sync? (In my client 'not synced' log I get: The item is not synced because of previous errors: Error downloading `FILE` - server replied: Internal Server Error (Redis server went away))

Thanks for any assistance!

Perhaps I should instead ask, what is needed to properly remove the redis server?  do I remove the 
'memcache.local' => '\\OC\\MEemcache\\APCu',?

I am planning to run without a redis server.

ANSWER:
After removing the memcache - redis  line, and the redis array in the config.php, I needed to stop the nextcloud container, rm the nextcloud container, and run the nextcloud container.  That seemed to do the trick.
