### ISSUE TITLE
[Nextcloud] Add php-ftp and smbclient

### ISSUE THREAD

**Issue by willtho89** [Wonderfall/dockerfiles#17]
Hi,

to use all features of the "external storage support" app, this container needs ftp and smb support.

Adding php7-ftp to the dockerfile should suffice for ftp support. 

I'm not as sure for smb support though. There is an libsmbclient-4.4.4-r0.apk in the alpine/edge/community repo but nextcloud might need a bit more then just this package.

**Comment by jazzdd86** [comment]
I would also vote for redis support used as memcache server and file locking. This works great and schould be implemented.

**Comment by Wonderfall** [comment]
About smb support : according to Nextcloud/ownCloud documentation, only `libsmbclient` is required on the server, and the PHP ext is recommended for reliability and performance. But it doesn't exist in Alpine repositories and I'm not even sure if such an extension is available for PHP 7, and even if it's available, I prefer ask Alpine rather than compiling myself. For now I'll add `libsmbclient`.
