### ISSUE TITLE
[rtorrent-flood] first time questions.

### ISSUE THREAD

**Issue by albaldi** [Wonderfall/dockerfiles#194]
Hi, I'd like to use your docker image, but have some doubts.
I have rtorrent running on my machine with:

```
directory = /home/USER/Downloads/torrent
session = /home/USER/Downloads/torrent/.rtorrent_session
```

How can I let rtorrent on docker use this directory?

Is it possible to edit rtorrent.rc inside docker?

What about DHT? There is no port info in _README.md_

And last: what is _docker-compose.yml_ and how should I use it?

Sorry for the questions, it's my first time with docker.
thanks.

**Comment by Wonderfall** [comment]
Mount `/home/USER/Downloads` as `/data` in the container. 

It is possible to use your own `rtorrent.rc`, in that particular case you should mount your own config file at `/home/torrent/.rtorrent.rc` instead of modifying it directly in the container.

DHT is not enabled by default because private trackers strongly advise against it.

`docker-compose.yml` is a YAML file for docker-compose, you should take a look at the docs : https://docs.docker.com/compose/
